import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
import joblib
import os

def clean_data(df):
    """
    Data Cleaning Module
    - duplicate removal
    - missing-value handling
    - invalid value detection
    """
    # Remove duplicates
    df = df.drop_duplicates()
    
    # Missing value handling for numeric columns
    numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
    imputer = SimpleImputer(strategy='median')
    df[numeric_cols] = imputer.fit_transform(df[numeric_cols])
    
    # Invalid value detection (ensure no negative values for counts)
    count_cols = ['patient_count', 'opd_count', 'ipd_count', 'disease_cases', 'current_stock', 'daily_consumption']
    for col in count_cols:
        if col in df.columns:
            df[col] = df[col].clip(lower=0)
            
    return df

def feature_engineering(df):
    """
    Feature Engineering Module
    - consumption trend
    - patient growth
    - disease growth
    - stock coverage days
    - seasonal features
    - weather features
    - PHC utilization score
    - disease pressure score
    """
    # Ensure data is sorted
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(by=['phc_id', 'medicine', 'date'])
    
    # Trend features
    df['consumption_trend'] = (df['previous_7_day_demand'] / 7) / (df['previous_30_day_demand'] / 30 + 1e-5)
    
    # Patient growth (7 day diff)
    df['patient_growth'] = df.groupby(['phc_id'])['patient_count'].pct_change(periods=7).fillna(0)
    df['disease_growth'] = df.groupby(['phc_id'])['disease_cases'].pct_change(periods=7).fillna(0)
    
    # Stock coverage days
    avg_daily_demand_7d = df['previous_7_day_demand'] / 7
    df['stock_coverage_days'] = df['current_stock'] / (avg_daily_demand_7d + 1e-5)
    
    # PHC Utilization and Disease Pressure
    df['phc_utilization_score'] = df['bed_occupancy'] * 0.7 + (df['ipd_count'] / (df['patient_count'] + 1e-5)) * 0.3
    df['disease_pressure_score'] = (df['disease_cases'] / (df['patient_count'] + 1e-5)) * (1 + df['mortality'])
    
    # Seasonality
    df['month'] = df['date'].dt.month
    df['day_of_week'] = df['date'].dt.dayofweek
    
    # We will create the target for PHC Health Risk model based on current data
    # 0 NORMAL, 1 WATCH, 2 HIGH, 3 CRITICAL
    conditions = [
        (df['disease_pressure_score'] > 0.6) | (df['stock_coverage_days'] < 2),
        (df['disease_pressure_score'] > 0.4) | (df['stock_coverage_days'] < 5),
        (df['disease_pressure_score'] > 0.2) | (df['stock_coverage_days'] < 10),
    ]
    choices = [3, 2, 1]
    df['health_risk'] = np.select(conditions, choices, default=0)
    
    # Clean up any inf values generated by division or pct_change
    df = df.replace([np.inf, -np.inf], 0)
    
    return df

def preprocess_pipeline(file_path):
    print("Loading data...")
    df = pd.read_csv(file_path)
    
    print("Cleaning data...")
    df = clean_data(df)
    
    print("Engineering features...")
    df = feature_engineering(df)
    
    # Encode categorical variables
    encoders = {}
    cat_cols = ['phc_id', 'state', 'district', 'city', 'medicine', 'medicine_category']
    for col in cat_cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        encoders[col] = le
        
    os.makedirs('models', exist_ok=True)
    joblib.dump(encoders, 'models/label_encoders.joblib')
    
    return df

if __name__ == "__main__":
    df = preprocess_pipeline('data/synthetic_arogyapulse_data.csv')
    df.to_csv('data/processed_data.csv', index=False)
    print("Preprocessing complete. Saved to data/processed_data.csv")
